spring.rabbitmq.host = ${RABBIT_MQ_HOST:192.168.1.80}
spring.rabbitmq.port = ${RABBIT_MQ_PORT:5672}
spring.rabbitmq.username = ${RABBIT_MQ_USERNAME:admin}
spring.rabbitmq.password = ${RABBIT_MQ_PASSWORD:admin}
spring.rabbitmq.virtual-host= ${RABBIT_MQ_VIRTUAL_HOST:wgh-dev}

server.port=${SERVER_PORT:8089}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://${MYSQL_ROOT_IP:192.168.110.80}:${MYSQL_ROOT_PORT:3306}/zhoil-yn-flight?autoReconnect=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
spring.datasource.username=${MYSQL_USERNAME:root}
#spring.datasource.password=${MYSQL_ROOT_PASSWORD:brysjhhrhl}

#\u673A\u573A\u533A\u57DF\u4EE3\u7801
flight.airport-3c=${FLIGHT_AIRPORT_3C:KMG}
flight.airport-code=${FLIGHT_AIRPORT_CODE:2901}

tflight_info_topic=${FLIGHT_TOPIC:flight}

spring.kafka.bootstrap-servers=${ZK_IP_PORT:192.168.1.80:9004}
spring.kafka.producer.retries=0
spring.kafka.producer.batch-size=16384
spring.kafka.producer.buffer-memory=33554432
spring.kafka.listener.poll-timeout=3000
spring.kafka.partitioner.class = com.higer.flightinfo.component.MyPartitioner
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.jpa.hibernate.ddl-auto=create
spring.jpa.database=mysql
spring.jpa.generate-ddl=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect
spring.datasource.password=1qaz@WSX#EDC