apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-service
  namespace: $NAMESPACE
  labels:
    app: $NAMESPACE
    service: websocket
spec:
  selector:
    matchLabels:
      service: websocket
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: websocket
    spec:
      containers:
        - name: websocket-service
          image: $REGISTRY/$NAMESPACE/websocket-service:SNAPSHOT-$BUILD_NUMBER
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1000m
              memory: 4096Mi
            limits:
              cpu: 1500m
              memory: 6144Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 30102
            initialDelaySeconds: 120
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 30102
            initialDelaySeconds: 120
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          ports:
            - containerPort: 30102
              name: http
          envFrom:
            - configMapRef:
                name: zhoil-yn-baseinfo
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  namespace: $NAMESPACE
spec:
  selector:
    service: websocket
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 30102
      targetPort: 30102
      nodePort: 30102