spring:
  application:
    name: FDDSService
  kafka:
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      bootstrap-servers: 172.16.1.7:9092,172.16.1.8:9092,172.16.1.9:9092
      #      bootstrap-servers: 127.0.0.1:9092
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level: ${LOGLEVEL:debug}

kafka:
  msgtopic: flight

ibmmq:
  hostname: 10.0.252.139
  channelname: SVRCONN.HY.TEST
  CCSID: 1208
  listener: 1414
  QMGRname: QMESB
  loginuser: ICPTestUser
  password:
  queue: FDDS_HY

millsTimeOut: 5000