# server
server.port=${SERVER_PORT:38080}
server.context-path=/base
# remote ip
remote.flight.ip=${REMOTE_FLIGHT_IP:127.0.0.1}
remote.flight.port=${REMOTE_FLIGHT_PORT:8081}
# map ip
remote.map.ip=${REMOTE_MAP_IP:127.0.0.1}
remote.map.port=${REMOTE_MAP_PORT:38080}
### ====================================================================== start
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8
# log
logging.config=classpath:log4j2-${LOG_LEVEL:debug}.properties
# mysql
spring.datasource.url=jdbc:mysql://${MYSQL_ROOT_IP:higer.wabob.com}:${MYSQL_ROOT_PORT:30001}/flight_login?useUnicode=true&characterEncoding=utf-8&useSSL=false
spring.datasource.username=${MYSQL_USERNAME:root}
spring.datasource.password=${MYSQL_ROOT_PASSWORD:123456}
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.tomcat.max-active=10
#redis
spring.redis.host=${REDIS_ROOT_IP:higer.wabob.com}
spring.redis.port=${REDIS_ROOT_PORT:30002}
spring.redis.password=${REDIS_ROOT_PASSWORD:}
spring.redis.timeout=${REDIS_ROOT_TIMEOUT:120000}
## mysql
#spring.datasource.url=jdbc:mysql://192.168.88.134:3306/zhoil_login?useUnicode=true&characterEncoding=utf-8
#spring.datasource.username=root
#spring.datasource.password=root111222
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
##redis
#spring.redis.host=192.168.88.134
#spring.redis.port=6379
#spring.redis.timeout=120000
### ====================================================================== end
spring.kafka.bootstrap-servers=${ZK_IP_PORT:172.16.16.191:9092}
spring.kafka.consumer.group-id=${KAFKA_GROUP_ID:test-consumer-group}
spring.kafka.consumer.auto-offset-reset=earliest
#spring.kafka.consumer.enable-auto-commit=true
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.auto-commit-interval=7000
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
token.expire.seconds:${TOKEN_EXPIRE_SECONDS:7200}
token.jwtSecret:${TOKEN_JWTSECRET:(ZH:)_$^&*79^%$_(OIL:)_@@++-45af7as%^-(ZUL:)_++++_.sds_(lala:)}
#\u6CB9\u6599\u53C2\u6570\u7C7B\u578B\uFF0C1\uFF1A\u6606\u660E\uFF0C0\uFF1A\u9ED8\u8BA4
fuel.type:${FUEL_TYPE:0}