
server.tomcat.uri-encoding=UTF-8
server.port=8084

# \u914D\u7F6E\u6570\u636E\u5E93\u4FE1\u606F
# mysql
spring.datasource.url=jdbc:mysql://${MYSQL_ROOT_IP:172.16.1.10}:${MYSQL_ROOT_PORT:3306}/flight_login?useUnicode=true&characterEncoding=utf-8&useSSL=false
spring.datasource.username=${MYSQL_USERNAME:root}
spring.datasource.password=${MYSQL_ROOT_PASSWORD:Abcd-1234}
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/zhoil_flight?useUnicode=true&characterEncoding=utf-8&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.initialSize=5
spring.datasource.minIdle=5
spring.datasource.maxActive=20
spring.datasource.maxWait=60000
spring.datasource.timeBetweenEvictionRunsMillis=60000
spring.datasource.minEvictableIdleTimeMillis=300000
spring.datasource.validationQuery=SELECT 1 FROM DUAL
spring.datasource.testWhileIdle=true
spring.datasource.testOnBorrow=false
spring.datasource.testOnReturn=false
spring.datasource.poolPreparedStatements=true
spring.datasource.maxPoolPreparedStatementPerConnectionSize=20
spring.datasource.filters=stat,wall,log4j
spring.datasource.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

#jpa
spring.jpa.database = MYSQL
spring.jpa.show-sql = true
spring.jpa.database-platform = org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.naming-strategy = org.hibernate.cfg.ImprovedNamingStrategy
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.ddl-auto = none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#redis
spring.redis.host=${REDIS_ROOT_IP:127.0.0.1}
spring.redis.port=${REDIS_ROOT_PORT:6379}
spring.redis.password=
spring.redis.timeout=${REDIS_ROOT_TIMEOUT:120000}
spring.redis.pool.max-idle=8
spring.redis.pool.min-idle=0
spring.redis.pool.max-active=8
spring.redis.pool.max-wait=-1

# 8:50-17:00 \u767D\u73ED    16:30:00
poll.time.bn=0 30 16 * * ?
# 8:50-17:00 \u961F\u957F
poll.time.bz=0 30 16 * * ?
# 8:50-17:00 \u526F\u961F
poll.time.bz1=0 30 16 * * ?
# b5b6   \u4E24\u4E2A\u65F6\u95F4\u6BB5 6:10 - 14:00
poll.time.c5c6=0 0 14 * * ?
#             3:30 - \u6B21\u65E5 9:30
poll.time.dn=0 30 9 * * ?
# ce = D1     12:30 - \u6B21\u65E59:30
poll.time.ce=0 30 9 * * ?
# \u591C\u73ED\u961F\u957F    15:50   -23:00    -\u6B21\u65E5 9:30
poll.time.dz=0 30 9 * * ?
# \u591C\u73ED\u526F\u961F\u957F 15:50-23:00  -\u6B21\u65E5 9:30
poll.time.dt=0 30 9 * * ?
# 8:50-\u6B21\u65E5 9:30
poll.time.c7=0 30 9 * * ?
# 6:30-\u6B21\u65E5 14:00
poll.time.c8=0 0 14 * * ?
# 8:50-\u6B21\u65E5 9:20
poll.time.c2=0 30 9 * * ?
# 12:30 - \u6B21\u65E5 9:20
poll.time.c20=0 30 9 * * ?
# 8:50-\u6B21\u65E5 9:20
poll.time.c1=0 30 9 * * ?

system_redis_start_date=${SYSTEMREDISSTARTDATE:2019-03-29}