
server.port=${SERVER_PORT:8079}

ribbon.eureka.enabled=false
zuul.routes.api-d.path=/base/**
zuul.routes.api-d.url=http://${REMOTE_LOGIN_IP:127.0.0.1}:${REMOTE_LOGIN_PORT:8080}/base
zuul.routes.api-f.path=/flight/**
zuul.routes.api-f.url=http://${REMOTE_FLIGHT_IP:127.0.0.1}:${REMOTE_FLIGHT_PORT:8081}/flight
zuul.routes.api-g.path=/map/**
zuul.routes.api-g.url=http://${REMOTE_MAP_IP:192.168.3.94}:${REMOTE_MAP_PORT:8082}/map
zuul.routes.api-s.path=/jobschedual/**
zuul.routes.api-s.url=http://${REMOTE_JOB_IP:127.0.0.1}:${REMOTE_JOB_PORT:7878}/jobschedual
zuul.routes.api-p.path=/print/**
zuul.routes.api-p.url=http://192.168.1.101:8686

zuul.host.connect-timeout-millis=${CONNECT_TIMEOUT_MILLIS:10000000}
zuul.host.socket-timeout-millis=${SOCKET_TIMEOUT_MILLIS:10000000}

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=${HYSTRIX_THREAD_TIMEOUTINMILLISECONDS:60000}

logging.config=classpath:log4j2-${LOG_LEVEL:debug}.properties

# mysql
spring.datasource.url=jdbc:mysql://${MYSQL_ROOT_IP:172.16.7.10}:${MYSQL_ROOT_PORT:3306}/${MYSQL_DATABASE:flight_login}?useUnicode=true&characterEncoding=utf-8&useSSL=false
spring.datasource.username=${MYSQL_USERNAME:root}
spring.datasource.password=${MYSQL_ROOT_PASSWORD:Abcd-1234}
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#redis
spring.redis.host=${REDIS_ROOT_IP:192.168.1.80}
spring.redis.port=${REDIS_ROOT_PORT:6379}
spring.redis.password=${REDIS_ROOT_PASSWORD:test123?*1}
spring.redis.timeout=${REDIS_ROOT_TIMEOUT:120000}
spring.redis.database=1

#redis
#spring.redis.host=192.168.88.134
#spring.redis.port=6379
#spring.redis.timeout=120000

token.expire.seconds: ${TOKEN_EXPIRE_SECONDS:7200}
token.jwtSecret: ${TOKEN_JWTSECRET:(ZH:)_$^&*79^%$_(OIL:)_@@++-45af7as%^-(ZUL:)_++++_.sds_(lala:)}
