# server
server.port=${SERVER_PORT:8081}
server.context-path=/flight


# remote ip
remote.login.ip=${REMOTE_LOGIN_IP:127.0.0.1}
remote.login.port=${REMOTE_LOGIN_PORT:8080}

### ====================================================================== start
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8

# log
logging.config=classpath:log4j2-${LOG_LEVEL:debug}.properties

redisson.address=${REDIS_ROOT_IP:172.16.9.16}:${REDIS_ROOT_PORT:6379}
## mysql
#spring.datasource.url=jdbc:mysql://${MYSQL_ROOT_IP:47.95.201.83}:${MYSQL_ROOT_PORT:3306}/zhoil_flight?useUnicode=true&characterEncoding=utf-8&useSSL=false
#spring.datasource.username=${MYSQL_USERNAME:root}
#spring.datasource.password=${MYSQL_ROOT_PASSWORD:root111222}
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.tomcat.max-active=10
#
##redis
#spring.redis.host=${REDIS_ROOT_IP:47.95.197.128}
#spring.redis.port=${REDIS_ROOT_PORT:6379}
#spring.redis.password=${REDIS_ROOT_PASSWORD:test123?*1}
#spring.redis.timeout=${REDIS_ROOT_TIMEOUT:120000}

# mysql
spring.datasource.url=jdbc:mysql://192.168.88.134:3306/zhoil_flight?useUnicode=true&characterEncoding=utf-8
spring.datasource.username=root
spring.datasource.password=root111222
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#redis
spring.redis.host=192.168.88.134
spring.redis.port=6379
spring.redis.timeout=120000
### ====================================================================== end

spring.kafka.bootstrap-servers=${ZK_IP_PORT:192.168.88.139:9092}
spring.kafka.consumer.group-id=${KAFKA_GROUP_ID:test-consumer-group}

spring.kafka.consumer.auto-offset-reset=earliest
#spring.kafka.consumer.enable-auto-commit=true
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.auto-commit-interval=5000

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

token.expire.seconds: ${TOKEN_EXPIRE_SECONDS:7200}
token.jwtSecret: ${TOKEN_JWTSECRET:(ZH:)_$^&*79^%$_(OIL:)_@@++-45af7as%^-(ZUL:)_++++_.sds_(lala:)}

#\u6839\u636E\u52A0\u6CB9\u5458ID\u83B7\u53D6\u4EFB\u52A1\u5217\u8868(\u5E73\u677F\u7AEF)\u662F\u5426\u5F00\u542F
staff_task_lock:${STAFF_TASK_LOCK:false}