# server
server.port=${SERVER_PORT:8083}
server.tomcat.uri-encoding=utf-8

# mysql
spring.datasource.user.url=jdbc:mysql://${MYSQL_ROOT_IP:192.168.56.101}:${MYSQL_ROOT_PORT:3306}/flight_login?useUnicode=true&characterEncoding=utf-8&useSSL=false
spring.datasource.user.username=${MYSQL_USERNAME:root}
spring.datasource.user.password=${MYSQL_ROOT_PASSWORD:123456}
spring.datasource.user.driver-class-name=com.mysql.jdbc.Driver



spring.datasource.flight.url=jdbc:mysql://${MYSQL_ROOT_IP:192.168.56.101}:${MYSQL_ROOT_PORT:3306}/flight_login?useUnicode=true&characterEncoding=utf-8&useSSL=false
spring.datasource.flight.username=${MYSQL_USERNAME:root}
spring.datasource.flight.password=${MYSQL_ROOT_PASSWORD:123456}
spring.datasource.flight.driver-class-name=com.mysql.jdbc.Driver


##########################  druid\u914D\u7F6E   ##########################
# \u4E0B\u9762\u4E3A\u8FDE\u63A5\u6C60\u7684\u8865\u5145\u8BBE\u7F6E\uFF0C\u5E94\u7528\u5230\u4E0A\u9762\u6240\u6709\u6570\u636E\u6E90\u4E2D# \u521D\u59CB\u5316\u5927\u5C0F\uFF0C\u6700\u5C0F\uFF0C\u6700\u5927
##################    \u8FDE\u63A5\u6C60\u914D\u7F6E    ################
#\u8FDE\u63A5\u6C60\u5EFA\u7ACB\u65F6\u521B\u5EFA\u7684\u521D\u59CB\u5316\u8FDE\u63A5\u6570
spring.datasource.druid.master.initial-size=5
#\u8FDE\u63A5\u6C60\u4E2D\u6700\u5927\u7684\u6D3B\u8DC3\u8FDE\u63A5\u6570
spring.datasource.druid.master.max-active=20
#\u8FDE\u63A5\u6C60\u4E2D\u6700\u5C0F\u7684\u6D3B\u8DC3\u8FDE\u63A5\u6570
spring.datasource.druid.master.min-idle=5
# \u914D\u7F6E\u83B7\u53D6\u8FDE\u63A5\u7B49\u5F85\u8D85\u65F6\u7684\u65F6\u95F4
spring.datasource.druid.master.max-wait=60000
# \u6253\u5F00PSCache\uFF0C\u5E76\u4E14\u6307\u5B9A\u6BCF\u4E2A\u8FDE\u63A5\u4E0APSCache\u7684\u5927\u5C0F
spring.datasource.druid.master.pool-prepared-statements=true
spring.datasource.druid.master.max-pool-prepared-statement-per-connection-size=20
#spring.datasource.druid.max-open-prepared-statements= #\u548C\u4E0A\u9762\u7684\u7B49\u4EF7
spring.datasource.druid.master.validation-query=SELECT 1 FROM DUAL
spring.datasource.druid.master.validation-query-timeout=30000
#\u662F\u5426\u5728\u83B7\u5F97\u8FDE\u63A5\u540E\u68C0\u6D4B\u5176\u53EF\u7528\u6027
spring.datasource.druid.master.test-on-borrow=false
#\u662F\u5426\u5728\u8FDE\u63A5\u653E\u56DE\u8FDE\u63A5\u6C60\u540E\u68C0\u6D4B\u5176\u53EF\u7528\u6027
spring.datasource.druid.master.test-on-return=false
#\u662F\u5426\u5728\u8FDE\u63A5\u7A7A\u95F2\u4E00\u6BB5\u65F6\u95F4\u540E\u68C0\u6D4B\u5176\u53EF\u7528\u6027
spring.datasource.druid.master.test-while-idle=true

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#\u673A\u573A\u4EE3\u7801
analyst.airport.codes=${ANALYST_AIPORT_CODES:2901,2902,2905,291F,2904,2903,2906,291K,291J,291H,291I,2909,2907,2908,291G}

#\u5BA2\u6237\u7AEF
export.tfuel.mandt=${FUEL_MANDT:800}
#ERP\u7528\u6237\u540D
export.tfuel.uname=${FUEL_NAME:YDLRJK}

spring.redis.host=${REDIS_ROOT_IP:192.168.56.101}

spring.redis.port=${REDIS_ROOT_PORT:6379}