status = error
dest = err
name = PropertiesConfig

property.myLevel=info

property.targeturl = /zhoil_log
property.filename = ${targeturl}/rolling/rollingOut.log

filter.threshold.type = ThresholdFilter
filter.threshold.level = ${myLevel}

appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} %c{1} - %C - %msg%n
appender.console.filter.threshold.type = ThresholdFilter
appender.console.filter.threshold.level = ${myLevel}

appender.rolling.type = RollingFile
appender.rolling.name = RollingFile
appender.rolling.fileName = ${filename}
appender.rolling.filePattern = ${targeturl}/rolling_gz/rollingOut-%d{MM-dd-yy}.log.gz
appender.rolling.layout.type = PatternLayout
appender.rolling.layout.pattern = [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} %c{1} - %C - %msg%n
appender.rolling.policies.type = Policies
appender.rolling.policies.time.type = TimeBasedTriggeringPolicy
appender.rolling.policies.time.interval = 1
appender.rolling.policies.time.modulate = true
appender.rolling.strategy.type = DefaultRolloverStrategy
appender.rolling.strategy.delete.type = Delete
appender.rolling.strategy.delete.basePath = ${targeturl}/rolling_gz
appender.rolling.strategy.delete.maxDepth = 2
appender.rolling.strategy.delete.iffile.type = IfFileName
appender.rolling.strategy.delete.iffile.glob = rollingOut-*.gz
appender.rolling.strategy.delete.iflastmodify.type = IfLastModified
appender.rolling.strategy.delete.iflastmodify.age = 3d

logger.rolling.name = com.zh
logger.rolling.level = ${myLevel}
logger.rolling.additivity = true
logger.rolling.appenderRef.rolling.ref = RollingFile


rootLogger.level = info
rootLogger.appenderRef.stdout.ref = STDOUT
rootLogger.appenderRef.rolling.ref = RollingFile
