server.tomcat.uri-encoding=UTF-8
server.port=20007
#============== kafka ===================
# \u6307\u5B9Akafka \u4EE3\u7406\u5730\u5740\uFF0C\u53EF\u4EE5\u591A\u4E2A        120.27.24.213:9092
spring.kafka.bootstrap-servers=${ZK_IP_PORT:192.168.56.101:9092}
#=============== consumer  =======================
# \u6307\u5B9A\u9ED8\u8BA4\u6D88\u8D39\u8005group id
spring.kafka.consumer.group-id=${KAFKA_GROUP_ID:schedule-consumer-group}
#spring.kafka.consumer.max-poll-records=3
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=true
spring.kafka.consumer.auto-commit-interval=1000
# \u6307\u5B9A\u6D88\u606Fkey\u548C\u6D88\u606F\u4F53\u7684\u7F16\u89E3\u7801\u65B9\u5F0F
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#redis
redisson.address=${REDIS_ROOT_IP:192.168.110.80}:${REDIS_ROOT_PORT:6379}
spring.redis.host=${REDIS_ROOT_IP:192.168.110.80}
spring.redis.port=${REDIS_ROOT_PORT:6379}
spring.redis.database=1
#spring.redis.password=${REDIS_ROOT_PASSWORD:test123?*1}
spring.redis.timeout=${REDIS_ROOT_TIMEOUT:120000}
### ====================================================================== end
# mysql
# mysql
spring.datasource.url=jdbc:mysql://${MYSQL_ROOT_IP:192.168.110.80}:${MYSQL_ROOT_PORT:3306}/${MYSQL_DATABASE:flight_login}?useUnicode=true&characterEncoding=utf-8&useSSL=false
spring.datasource.username=${MYSQL_USERNAME:root}
spring.datasource.password=${MYSQL_ROOT_PASSWORD:higer0702}
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
token.expire.seconds:${TOKEN_EXPIRE_SECONDS:18000}
token.jwtSecret:${TOKEN_JWTSECRET:(ZH:)_$^&*79^%$_(OIL:)_@@++-45af7as%^-(ZUL:)_++++_.sds_(lala:)}


